/* data.js — JourneyForever
   No hardcoded itineraries — all content generated by Gemini on demand.
   This file holds UI constants, INR pricing, and destination suggestions. */

export const ACTIVITY_ICONS = { Morning: "🌅", Afternoon: "☀️", Evening: "🌙" };
export const CATEGORY_ICONS = {
  sightseeing: "🏛️", food: "🍜", adventure: "🧗", culture: "🎭",
  nature: "🌿", shopping: "🛍️", nightlife: "🌙",
};

// INR per person per day
export const BUDGET_RATES  = { budget: 3500, mid: 8500, luxury: 25000 };
export const BUDGET_LABELS = { budget: "🎒 Budget", mid: "✈️ Mid-Range", luxury: "💎 Luxury" };

// Format INR with ₹ symbol and Indian number system (e.g. ₹1,25,000)
export function formatINR(amount) {
  return "₹" + amount.toLocaleString("en-IN");
}

// Popular destination suggestions — img uses stable Unsplash photo IDs
export const SUGGESTED_DESTINATIONS = [
  { destName: "Rajasthan",    country: "India",        emoji: "🏰", color: "#C8472A", blurb: "Land of maharajas — forts, palaces, deserts and vivid culture",      img: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400&q=80" },
  { destName: "Tokyo",        country: "Japan",        emoji: "🗼", color: "#DB2777", blurb: "Neon-lit megacity where ancient temples meet anime culture",           img: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80" },
  { destName: "Paris",        country: "France",       emoji: "🗼", color: "#7C3AED", blurb: "City of light, love, and world-class cuisine",                         img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=80" },
  { destName: "Bali",         country: "Indonesia",    emoji: "🌺", color: "#7C3AED", blurb: "Tropical paradise of rice terraces, temples and surf",                 img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80" },
  { destName: "New York",     country: "USA",          emoji: "🗽", color: "#0891B2", blurb: "The city that never sleeps — culture, food and energy",                img: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=400&q=80" },
  { destName: "Santorini",    country: "Greece",       emoji: "🏛️", color: "#2563EB", blurb: "Volcanic island famous for white-washed cliffs and sunsets",           img: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400&q=80" },
  { destName: "Marrakech",    country: "Morocco",      emoji: "🕌", color: "#D97706", blurb: "Ancient medina of spices, souks, and riads",                           img: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=400&q=80" },
  { destName: "Cape Town",    country: "South Africa", emoji: "🦁", color: "#16A34A", blurb: "Where mountains meet ocean at the tip of Africa",                      img: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=400&q=80" },
  { destName: "Kyoto",        country: "Japan",        emoji: "🏯", color: "#C8472A", blurb: "Japan's ancient capital of temples, geishas and bamboo groves",        img: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400&q=80" },
  { destName: "Amalfi Coast", country: "Italy",        emoji: "⛵", color: "#0891B2", blurb: "Dramatic cliffside villages above the sparkling Tyrrhenian Sea",       img: "https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=400&q=80" },
  { destName: "Dubai",        country: "UAE",          emoji: "🏙️", color: "#D97706", blurb: "Futuristic desert city of luxury, architecture and ambition",          img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400&q=80" },
  { destName: "Lisbon",       country: "Portugal",     emoji: "🎵", color: "#C8472A", blurb: "Soulful city of fado music, trams and Atlantic views",                 img: "https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?w=400&q=80" },
];
